---
- name: configuring web server
  hosts: web
  become: yes
  tasks:
    - name: install webserver
      dnf:
        name: httpd
        state: installed
    - name: start & enable service
      service:
        name: httpd
        state: started
        enabled: yes
    - name: copy index.html
      ansible.builtin.copy:
        src: /home/vijay/workspace/ragav/index.html
        dest: /var/www/html/index.html
